### ISSUE TITLE
Exception: Internal error, please try again later.

### ISSUE THREAD

**Issue by hop-soellingeraj** [diffgram/python-sdk#13] opened 2021-09-20 20:17 UTC
I am having an issue.  Wondering if anyone knows why I get Internal Error.  I am trying to export the labels for a specific dataset called `181344_Frame2000`. 

```python
from diffgram import Project

project = Project()
first_dir = project.directory.get("181344_Frame2000")

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
/var/folders/xs/144pgszn7359w3wj1_cdn0pc0000gp/T/ipykernel_99896/2784511900.py in <module>
----> 1 first_dir = project.directory.get("181344_Frame2000")
      2 
      3 # TODO replace `apples` with desired search term
      4 file_list = first_dir.list_files(
      5     search_term="jpg")

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/diffgram/core/directory.py in get(self, name)
    327                 # to use object approach (over dict)
    328 
--> 329                 new_directory = Directory(client = self.client)
    330                 refresh_from_dict(new_directory, directory_json)
    331 

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/diffgram/core/directory.py in __init__(self, client, file_id_list_sliced, init_file_ids, validate_ids)
     86         elif file_id_list_sliced is not None:
     87             self.file_id_list = file_id_list_sliced
---> 88         super(Directory, self).__init__(self.client, self.file_id_list, validate_ids)
     89 
     90     def all_files(self):

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/diffgram/core/diffgram_dataset_iterator.py in __init__(self, project, diffgram_file_id_list, validate_ids, max_size_cache, max_num_concurrent_fetches)
     27         self._internal_file_list = []
     28         if validate_ids:
---> 29             self.__validate_file_ids()
     30         self.current_file_index = 0
     31 

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/diffgram/core/diffgram_dataset_iterator.py in __validate_file_ids(self)
     88         if not self.diffgram_file_id_list:
     89             return
---> 90         result = self.project.file.file_list_exists(self.diffgram_file_id_list, use_session = False)
     91         if not result:
     92             raise Exception(

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/diffgram/file/file_constructor.py in file_list_exists(self, id_list, use_session)
    425                 auth = HTTPDigestAuth(self.client.client_id, self.client.client_secret)
    426             )
--> 427         self.client.handle_errors(response)
    428 
    429         response_json = response.json()

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/diffgram/core/core.py in handle_errors(self, response)
    164 
    165                 if response.status_code == 500:
--> 166                         raise Exception("Internal error, please try again later.")
    167 
    168                 raise_for_status = response.raise_for_status()

Exception: Internal error, please try again later.
```

**Comment by PJEstrada** [comment] 2021-09-20 21:18
Hi @hop-soellingeraj,

This seems to be a permissions issue. May I ask if you have "Editor" or "Viewer" Permissions in the project?

**Comment by anthony-chaudhary** [comment] 2021-09-20 21:52
Fixed via https://github.com/diffgram/python-sdk/pull/14

**Comment by PJEstrada** [comment] 2021-09-20 22:59
Hi! @hop-soellingeraj ,

Can you please update to version 0.4.15 and try if the issue is solved for you?

**Comment by hop-soellingeraj** [comment] 2021-09-23 19:59
Yes, this was solved.  I ran into another issue though.  Same error message, but different situation:
```python
job = project.job.get_by_id(id='2532')
data = job.generate_export(return_type='url')

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
/var/folders/xs/144pgszn7359w3wj1_cdn0pc0000gp/T/ipykernel_19834/2139514786.py in <module>
      1 job = project.job.get_by_id(id='2532')
----> 2 data = job.generate_export(return_type='url')

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/diffgram/job/job.py in generate_export(self, kind, return_type, wait_for_export_generation)
    413                                             json=spec_dict)
    414 
--> 415         self.client.handle_errors(response)
    416 
    417         data = response.json()

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/diffgram/core/core.py in handle_errors(self, response)
    168 
    169                 if response.status_code == 500:
--> 170                         raise Exception("Internal error, please try again later.")
    171 
    172                 raise_for_status = response.raise_for_status()

Exception: Internal error, please try again later.
```

**Comment by anthony-chaudhary** [comment] 2021-09-25 05:32
Fixed in https://github.com/diffgram/python-sdk/releases/tag/0.4.16
Thanks for this!

I'll make some further new issues related to this

**Closed as completed by anthony-chaudhary** 2021-09-25 05:32 UTC
